Feat/request page のデザインを調整
traPtitech/Jomon-UI pull request #190
Opened 2024-06-29 04:17 UTC by reiroop

- フィルターが一時的に消えています
- タイトル部分が左寄せになりました
- 列要素にpaddingが追加されています
- 一部表記が変更されました

2024-06-29 05:13 UTC, mehm8128 reviewed
気になったところ雑にレビューしました
Figmaでauto layoutになってるところは基本flexかgridで作ってpaddingとかgapとかでスペーシングして、できるだけmarginとかはつけないように修正するときれいになりそうです(Figma適当だった頃に昔の僕がmarginつけてたのが悪いけど)

2024-06-29 05:13 UTC, mehm8128 commented on src/pages/RequestsPage.vue
> +      <div class="relative flex w-full items-center justify-start gap-7">
absolute消したのでrelativeもいらなくなってそうです

2024-06-29 05:13 UTC, mehm8128 commented on src/pages/RequestsPage.vue
> +    <div class="min-w-160 flex flex-col">
このdiv消すか、1つ下のタグとマージしちゃっていい気がします

2024-06-29 10:27 UTC, reiroop commented on src/components/requests/RequestItem.vue
>        <div class="text-right text-3xl">{{ totalAmount }}円</div>
ありがとうございます

2024-07-01 11:29 UTC, mehm8128 commented
/review

2024-07-01 11:30 UTC, mehm8128 commented
/improve

2024-07-22 02:53 UTC, mehm8128 commented
マージミスってそうですが大丈夫ですか？
`git reset --hard b59aa7d`で直るかな

2024-08-22 02:07 UTC, reiroop commented
> マージミスってそうですが大丈夫ですか？ `git reset --hard b59aa7d`で直るかな

直せました、ありがとうございます

2024-08-22 12:23 UTC, mehm8128 commented on src/components/shared/TagsGroup.vue
> +      class="inline-block border-dark-600 rounded border p-0.5 mr-1.5 mb-1.5">
元のままで`class="flex items-center gap-2"`に`flex-wrap`を追加するだけでも意図した動きになりそうです？

2024-08-22 12:23 UTC, mehm8128 commented
作業中ならすぐじゃなくても大丈夫ですが、conflictの解消もお願いします🙏

2024-08-23 09:53 UTC, reiroop commented on src/components/shared/TagsGroup.vue
> +      class="inline-block border-dark-600 rounded border p-0.5 mr-1.5 mb-1.5">
知りませんでした...ありがとうございます

2024-09-07 02:23 UTC, reiroop commented
/review

2024-09-07 02:23 UTC, reiroop commented
/improve

2024-09-08 02:34 UTC, reiroop commented
スマホサイズの時に
- PaginationBarの表示を省略する
- StatusChipの左右のpaddingを消す
- 全体の左右のpadding/marginを減らす(表示)

2024-09-28 12:55 UTC, mehm8128 reviewed
tailwind移行時に壊れたっぽいところメインですがちょっと気になったところ書きました
あとはそんなに問題なさそうです

2024-09-28 12:55 UTC, mehm8128 commented on src/components/requests/RequestItem.vue
> +            <UserIcon class="max-w-7" :name="userMap[request.createdBy]" />
アイコンが丸くなってなさそう
tailwindにしたときに壊れたのかも？
![image](https://github.com/user-attachments/assets/2bf51965-b0ad-493d-8ca3-75e5ed7fef25)

2024-09-28 12:55 UTC, mehm8128 commented on src/components/requests/RequestItem.vue
>        <StatusChip :status="request.status" />
status chip
- 完全な丸になってなさそう
- Figmaで中身塗りつぶさないやつ使ってるので、そっちの方がいいかもです
![image](https://github.com/user-attachments/assets/33c458cd-c6a6-48b7-950a-0f6abb365bb3)

2024-09-28 12:55 UTC, mehm8128 commented on src/pages/RequestsPage.vue
> +            class="hover:hover-secondary first:hover:rounded-t-xl last:hover:rounded-b-xl">
`hover:`が効いてなさそうです
多分これもtailwind移行時に壊れたっぽい？

2024-12-21 10:54 UTC, anko9801 requested changes

2024-12-21 10:54 UTC, anko9801 commented on src/components/requests/RequestItem.vue
> +    <div class="flex flex-grow flex-wrap">
折り返したときに右側が空いてしまうのが気になります。これはまだデザインが決まってないので別 PR でレスポンシブデザインにするのが筋かなと思います。
![image](https://github.com/user-attachments/assets/dbbd0a67-2f32-4765-9316-788a4007b68a)

2024-12-21 10:54 UTC, anko9801 commented on src/pages/RequestsPage.vue
> +  <div class="max-w-6xl mx-auto p-3 sm:p-8 flex flex-col gap-7">
ここは App.vue のところを書き換えて全ページでデザインを共通化した方がのちのち楽だと思うので別 PR でお願いしたいです 🙏

2024-12-21 10:54 UTC, anko9801 approved these changes

2025-05-06 07:26 UTC, merged