Feat/request details
traPtitech/Jomon-UI pull request #5
Opened 2022-02-12 11:44 UTC by mehm8128

2022-04-06 12:20 UTC, mehm8128 commented on src/components/RequestLog.vue
> +            {{
ここらへんCtrl+Sするたびに改行される謎のバグ発生中です...

2022-04-12 17:25 UTC, FujishigeTemma commented
#6 の変更が混ざってるので、それをマージしてからレビューしたいです。

2022-04-16 07:38 UTC, mehm8128 commented on src/md/clubBudgetRequest.md
> +# 部費利用申請
MDテンプレート、どんな感じがいいのか分からなかったので種類増やしたり内容変えたりとかした方がよさそうですかね

2022-04-19 22:18 UTC, FujishigeTemma commented on src/md/clubBudgetRequest.md
> +# 部費利用申請
どんなテンプレートが良いかは後で話し合って追加するので良さそうです。とりあえず動かすのに必要そうなのを適当に使ってもらえれば:pray:

2022-04-19 22:20 UTC, FujishigeTemma commented
これなんかめっちゃいろんな変更入ってません？[cb0513d](https://github.com/traPtitech/Jomon-UI/pull/5/commits/cb0513df0f4e9b0f762fcdb36f21a748541fe336)が悪そうな気がします。
直せなさそうだったらまた相談してください。

2022-05-07 05:04 UTC, mehm8128 commented on src/components/shared/MarkdownIt.vue
> +  <div class="text-sm prose break-words" v-html="md.render(text)"></div>
proseを入れないとmarkdownが効かないけどproseを入れるとNewRequestModalでプレビュー表示の幅が小さくなってしまいました

2022-05-09 07:25 UTC, FujishigeTemma requested changes
30%ぐらいしか見れてないけどとりあえずコメントしました

2022-05-09 07:25 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +const id = String(route.params.id)
これ、もう少し適切にハンドリングする必要がありそうです(toPageみたいに切り出して書いて欲しい)

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/Tags.vue
> +  <span v-if="limit !== 0 && tags.length > limit"> ...</span>
ロジックは簡単なもの以外はscript内に書いて欲しい

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/StatusChip.vue
> +}
enumっぽいやつには極力型をつけて欲しい

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/StatusChip.vue
> +      class="text-gray-500 w-8" />
これ親につけたら継承されないかな？

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/Modal.vue
> +<script lang="ts" setup>
ライブラリのPR生えてたし後で見ます

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/FixButton.vue
> +<script lang="ts" setup>
FixよりEditのほうが良さそう？

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/MarkdownIt.vue
> +  breaks: true
`linkify: true`もほしい

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/Button.vue
>  <script lang="ts" setup>
rebaseしたときにrollbackしてそう

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/RequestDetail.vue
> +<script lang="ts" setup>
もう少しコンポーネントに切って欲しい

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/RequestFilteringMenu.vue
> +<script lang="ts" setup>
ここももう少しコンポーネントに切り出して欲しい

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/NewRequestModal.vue
> +<script lang="ts" setup>
ここももう少しコンポーネントに切り出して欲しい

2022-05-09 07:25 UTC, FujishigeTemma commented on src/components/shared/MarkdownIt.vue
> +  <div class="text-sm prose break-words" v-html="md.render(text)"></div>
レビューにも書いたけどNewRequestはページとして切り出したいです
切り出したあとで治ってなかったら、その時考えるのでいいですか？

2022-05-09 09:55 UTC, mehm8128 commented on src/stores/request.ts
> +      }
GETのフィルターは「複数の場合カンマ区切り」って書いてあったのでこれで大丈夫だと思います

2022-05-09 10:01 UTC, mehm8128 commented on src/pages/Requests.vue
> +  userStore.fetchMe()
ですね

2022-05-09 10:16 UTC, mehm8128 commented on src/components/shared/StatusChip.vue
> +      class="text-gray-500 w-8" />
すみません、どれのことですか？
text-*のことであれば「承認待ち」とかの文字も色変わります(それでもいいかもです)
w-8のことであれば表示がおかしくなっちゃいます

2022-05-09 10:24 UTC, mehm8128 commented
https://github.com/traPtitech/Jomon-UI/pull/5#discussion_r867708851
分かりました

2022-05-09 10:45 UTC, mehm8128 commented on src/stores/request.ts
> +      ).data
string型を渡しなさいって怒られちゃいます

2022-05-09 11:02 UTC, mehm8128 commented on src/stores/tag.ts
> +    isTagFetched.value = true
fetch関数の中に書くことにします

2022-05-09 11:08 UTC, mehm8128 commented on src/stores/request.ts
> +import { defineStore } from 'pinia'
代わりにpages/Request.vueに書くみたいな感じですか？

2022-05-10 06:01 UTC, FujishigeTemma commented on src/stores/request.ts
> +      ).data
あー、なるほど
なんかもうちょい良さげになる気がするのでちょい考えておきます

2022-05-10 06:01 UTC, FujishigeTemma commented on src/stores/request.ts
> +      }
OK

2022-05-10 06:02 UTC, FujishigeTemma commented on src/stores/request.ts
> +import { defineStore } from 'pinia'
そうだね

2022-05-10 06:03 UTC, FujishigeTemma commented on src/components/shared/StatusChip.vue
> +      class="text-gray-500 w-8" />
なるほど。次にレビューするときに確認しておきます。

2022-05-10 11:46 UTC, mehm8128 commented on src/stores/request.ts
> +import { defineStore } from 'pinia'
FetchRequestとかそれに関係するParamsとかが明らかにやばそうな書き方になってしまいましたどうしましょう...
tagをカンマ区切りじゃなくて普通に配列で渡すようにすればもう少し簡潔になりそうです多分

2022-05-10 12:20 UTC, mehm8128 commented on src/stores/transaction.ts
> +  const fetchTransactions = async (sort: string) =>
これtransactionなので、できればtemmaさんにtransactionブランチで修正していただきたいです🙏

2022-05-10 12:21 UTC, mehm8128 commented on src/stores/transaction.ts
> +  const fetchTransactions = async (sort: string) =>
と思ったけどこのストア作ったのこのブランチだったのでやっときます

2022-05-10 13:02 UTC, mehm8128 commented on src/stores/transaction.ts
> +  const fetchTransactions = async (sort: string) =>
ここ、sort以外にもオプションあるのに暫定的に書いてただけっぽいので、やっぱりtransactionのフィルタリング作るときにそちらでお願いしたいです

2022-05-18 06:50 UTC, mehm8128 commented
https://github.com/traPtitech/Jomon-UI/pull/5#discussion_r872965564
コンポーネントの分け方が微妙だからかもなのですが、requestDetailStoreをstore使わずに書くと編集モードの切り替えとかが結構複雑になっちゃいそうで、store使った方が楽なんですよね...(切り替え方の方に問題があるかもですが)

2022-05-22 03:58 UTC, mehm8128 commented on src/components/NewComment.vue
> +    </details>
これ、タブで切り替えるようにすると、入力しながらプレビュー見れないのでやや不便だと思ったのですがどうですか？

2022-05-22 11:32 UTC, mehm8128 commented on src/components/NewComment.vue
> +  postComment(requestDetailStore.request.id, comment.value)
エラーハンドリングってどんな感じにすればいいですか？
調べたらtry-catchを使う書き方が出てきたのですがそれで大丈夫ですか？

2022-05-24 13:22 UTC, mehm8128 commented
https://github.com/traPtitech/Jomon-UI/pull/5#discussion_r880313822
なるほど、確かにそうですね、それでよさそうです！

2022-05-24 13:28 UTC, FujishigeTemma commented on src/components/CommentLog.vue
> +  <div class="m-2 p-2 border border-zinc-300">
コメントだけ囲ってある方が自然な気がしますがどうでしょう？

2022-05-24 13:28 UTC, FujishigeTemma commented on src/components/CommentLog.vue
> +      class="ml-12"
縦を揃えたい&&コメント部分をインデントしたい的なモチベなら、この場合はmarginじゃなくてdomの配置で実現するようにして欲しい

2022-05-24 13:28 UTC, FujishigeTemma commented on src/components/CommentLog.vue
> +            )
DateTimeに加工するところからformat~の責務にして欲しい。あと、formattedみたいな変数を用意するほうが読みやすい気がする

2022-05-24 13:28 UTC, FujishigeTemma commented on src/components/CommentLog.vue
> +      <span class="text-zinc-400">
textのカラーの使い分けは意味的に統一したいので先に決めてしまうか、黒で統一してあとから使い分けるようにして欲しい。実際に書くときは、windi.config.tsに`text-primary: text-zinc-~`みたいなエイリアスを作るのが良いと思う。

2022-05-24 13:28 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +<script lang="ts" setup>
ファイル名、複数形になってるのは間違い？

2022-05-24 13:28 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +import { ref } from 'vue'
```suggestion
import { onMounted, ref } from 'vue'
```

2022-05-24 13:28 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +import { toId } from '../lib/parsePathParams'
```suggestion
import RequestDetailLower from '/@/components/RequestDetailLower.vue'
import { toId } from '/@/lib/parsePathParams'
```

2022-05-24 13:28 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +    <RequestDetailLower />
意味的に以下に分けられるもの（分け方は割と一例なのでもう少し自分で考えてみたほうが良いかも）を見た目の位置で分けちゃってるので分け方？命名の仕方？があんまり良くな息がします。以下をコンポーネントに分けてあるいはまとめて、それをここでうまく配置してあげるというやり方にすると良いと思います。（考えてるよりもっと細かい単位でコンポーネントに切って良いです）
- 変更できるタイトル
- 状態表示
- 状態変更系ボタン
- 各種メタ情報
  - グループ
  - 申請者
  - 申請日
  - 申請金額
  - 対象者
- タグ一覧
- 詳細

2022-05-24 13:28 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +  <div class="pt-4 px-12">
ここも他のページと同じような画面配置にして欲しい。↓みたいなやつ（タイトルとかはなくしてもいいけど）
```
  <div>
    <div class="flex flex-col mx-auto min-w-160 w-2/3">
      <div class="py-8">
        <h1 class="text-center text-3xl">グループの新規作成</h1>
      </div>
      ...
```

2022-05-24 14:35 UTC, mehm8128 commented on src/pages/RequestDetails.vue
> +import { ref } from 'vue'
これ、eslintの@typescript-eslint/no-duplicate-importsでエラー吐くようにできそうなのと、unused-imports/no-unused-importsで使ってないimport消せそうなのでどっちも入れたいのですが、手元でやったところなぜかファイル保存時に自動で整形してくれなかったので入れてみてほしいです🙏

2022-05-24 14:43 UTC, mehm8128 commented on src/pages/RequestDetails.vue
> +import { ref } from 'vue'
あ、後者もできましたー

2022-05-24 15:00 UTC, FujishigeTemma commented on src/pages/RequestDetails.vue
> +import { ref } from 'vue'
:pro:、ありがとうございます

2022-05-24 15:04 UTC, mehm8128 commented on src/components/CommentLog.vue
> +      class="ml-12"
分かりました、ありがとうございます
やってみます

2022-05-24 15:05 UTC, mehm8128 commented on src/pages/RequestDetails.vue
> +<script lang="ts" setup>
あー、間違いっぽそうなので修正します

2022-05-24 15:33 UTC, mehm8128 commented on src/components/CommentLog.vue
> +      <span class="text-zinc-400">
とりあえず全部黒で統一しておきます

2022-05-25 09:41 UTC, mehm8128 commented on src/components/NewRequestContentForm.vue
> +<script lang="ts" setup>
「テンプレートの選択時にcontentを置き換えるようなコンポーネントだけにする」というのが分からなかったのですが、詳細を入力するtextarea要素は親(NewRequest.vue)に置いておいて、テンプレートを選択するVue-Selectの要素はコンポーネント化しておくということですか？

2022-05-25 09:42 UTC, mehm8128 commented on src/pages/RequestDetails.vue
> +    <RequestDetailLower />
なるほど、理解しました。もうちょっと考えて細かくコンポーネント化してみます

2022-09-03 06:06 UTC, mehm8128 commented
メモ
画像以外のファイルについても作成&表示&ダウンロード対応する

2022-10-09 17:46 UTC, FujishigeTemma reviewed
量が多くなりすぎちゃったので、動いてそうなら一回マージしちゃって大丈夫です。他のとこと変更する際に気になったところがあったら少しずつ直していく方針にしたいです。

2022-10-09 17:46 UTC, FujishigeTemma approved these changes

2022-10-12 01:09 UTC, mehm8128 commented
コンフリクト解消したら一旦マージして、そのあとでPR立ててgroup detailで指摘されたのと似たようなところを修正する形で大丈夫ですか？

2022-10-12 02:12 UTC, FujishigeTemma commented
大丈夫です

2022-10-12 02:24 UTC, mehm8128 commented
コンフリクトとコミットが多すぎてやばいのでrebaseじゃなくてmergeで大丈夫ですか...？それとも時間かけてでもrebaseした方がいいですか？

2022-10-12 04:31 UTC, FujishigeTemma commented
いや、マージで良いよ🙆‍♂️

2022-10-12 06:00 UTC, mehm8128 commented
なんか今まで出てなかったTypeエラーが全部の@clickとかで出てそうです...

2022-10-12 09:55 UTC, mehm8128 commented
ので一旦マージします

2022-10-12 09:56 UTC, merged