Feat/groups
traPtitech/Jomon-UI pull request #6
Opened 2022-03-03 08:22 UTC by mehm8128

2022-04-04 14:14 UTC, FujishigeTemma commented
swaggerから生成した型や関数を使ったものに書き換えてほしいです:pray:
その後で見ます:man_bowing:

2022-04-04 14:15 UTC, FujishigeTemma commented
グループの追加ページはモーダルでなく`/groups/new`にページとして作成

2022-04-11 11:06 UTC, FujishigeTemma requested changes

2022-04-11 11:06 UTC, FujishigeTemma commented on index.html
> +  <body style="color: #333333">
全体に継承させたいやつはApp.vue以下の`<main>`とかに当ててほしいです。

2022-04-11 11:06 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +
入力タイトルは入力欄の左上に乗せて、入力欄が揃うようにして欲しいです

2022-04-11 12:09 UTC, mehm8128 commented on src/stores/group.ts
> +  const groupOwners = ref<string[]>([])
ここらへんはグループの詳細画面を実装時に使うつもりですが、メンバーやオーナーをグループのGETに含めるならそこらへんはいらなさそうですね

2022-04-11 12:11 UTC, mehm8128 commented on src/components/Group.vue
> +</template>
昔の自分はなんでこんな実装したんですかね...

2022-04-11 12:12 UTC, mehm8128 commented on index.html
> +  <body style="color: #333333">
前に修正したはずがなぜかできてませんでした...

2022-04-12 17:03 UTC, FujishigeTemma requested changes

2022-04-12 17:03 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +    <h1 class="text-3xl text-center mt-4 mb-12">グループの新規作成</h1>
タイトルの縦幅とかDOM構造とかは他のページと極力統一してほしいです。特に遷移元とか、ネストの親とか。

2022-04-12 17:03 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +        <span>グループ名</span>
`text-base`ぐらいのサイズで良さそう

2022-04-12 17:03 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +      </div>
左/右端のほうが良さそうです

2022-04-13 10:57 UTC, mehm8128 commented on src/pages/NewGroup.vue
> +        <span>グループ名</span>
「グループ名」のところですか？それだとちょっと小さい気がしました

2022-04-13 11:51 UTC, mehm8128 commented on src/pages/NewGroup.vue
> +    <h1 class="text-3xl text-center mt-4 mb-12">グループの新規作成</h1>
遷移元って何のことですか？

2022-04-14 06:14 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +    <h1 class="text-3xl text-center mt-4 mb-12">グループの新規作成</h1>
/Aから/Bに移動するときの/Aを遷移元、/Bを遷移先って読んでました。

2022-04-14 07:18 UTC, mehm8128 commented on src/pages/NewGroup.vue
> +    <h1 class="text-3xl text-center mt-4 mb-12">グループの新規作成</h1>
なるほどです

2022-04-15 20:51 UTC, FujishigeTemma commented on src/components/shared/PaginationBar.vue
> +<template>
すいません、ホントは良くないんですが言葉にするのが面倒だったのでここまでで指摘したことも含めて一旦プッシュしました。
Diffを見て、わからない所があれば聞いてください。結構、リファクタしてあるので読んでくれると嬉しいです。

2022-04-15 23:08 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +    <div class="flex flex-col justify-between mt-8 ml-12 mr-12 text-xl h-4/5">
Groupsを参考になおしてみて欲しい:pray:
```suggestion
  <div class="pt-8 px-60 h-full">
    <h1 class="text-3xl text-center">グループの新規作成</h1>
    <div class="flex flex-col justify-between mt-8 ml-12 mr-12 text-xl h-4/5">
```

2022-04-15 23:08 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +      </div>
`rounded`欲しい

2022-04-15 23:08 UTC, FujishigeTemma commented on src/pages/NewGroup.vue
> +          class="border border-gray-300 resize-none" />
```suggestion
          class="border border-gray-300 h-36" />
```

2022-04-16 07:42 UTC, mehm8128 commented on src/components/shared/PaginationBar.vue
> +<script lang="ts" setup>
ホバー時に文字の色変わるのやや分かりにくい気がしたのですがどうですか？
修正前みたいに枠で囲うとか背景色変えるとかの方がいい気がしました

2022-04-16 08:59 UTC, FujishigeTemma commented on src/components/shared/PaginationBar.vue
> +<script lang="ts" setup>
そうかもです。前の感じに戻してみました。

2022-04-16 09:02 UTC, FujishigeTemma approved these changes
良さそうです！！:kansya:
transactionが微妙に依存しててマージしたいので細かいとこだけ修正してマージします。
ページングのスタイルみたいになんか気になるところあれば、#12でお願いします:pray:

2022-04-16 09:02 UTC, merged