Feat/admin page
traPtitech/Jomon-UI pull request #7
Opened 2022-03-03 08:22 UTC by mehm8128

2022-04-04 13:50 UTC, FujishigeTemma requested changes

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +    userStore.getUsers()
とりあえずは気にしなくていいですが、ローディング時の表示には`<Suspense>`なんかも使えます。
https://vuejs.org/guide/built-ins/suspense.html

2022-04-04 13:50 UTC, FujishigeTemma commented on src/App.vue
> +          <router-link to="/transactions?pageIndex=1"
query parameterはoptionalにして、component側でdefault valueを定義するようにしてほしいです。

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +import { useUserStore } from '../stores/user'
`/@`が`/src`のaliasとして登録されているので、依存をわかりやすくするため、同階層以下のものを使う時以外は`/@`を使ってください（つまり、`/src`や'../'を使わない）。
```suggestion
import Button from '/@/components/shared/Button.vue'
import VueSelect from '/@/components/shared/VueSelect.vue'
import { useAdminStore } from '/@/stores/admin'
import { useUserStore } from '/@/stores/user'
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +    <h1 class="text-3xl text-center mt-4 mb-4">管理ページ</h1>
```suggestion
    <h1 class="text-3xl text-center my-4">管理ページ</h1>
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/components/shared/Button.vue
> +      'hover:bg-zinc-200 rounded-lg border border-zinc-300 border-2 ' +
```suggestion
      'hover:bg-zinc-200 rounded-md border border-zinc-300' +
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +            class="border border-solid border-black pr-2 pl-2 rounded-md inline-block text-center"
```suggestion
            class="border border-black px-2 rounded text-center"
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +      </ul>
```suggestion
      <ul class="flex gap-2">
        <li v-for="admin in admins" :key="admin">
          <div
            class="border border-solid border-black pr-2 pl-2 rounded-md inline-block text-center"
          >
            {{ admin }}
          </div>
        </li>
      </ul>
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +        placeholder="管理者を追加"
```suggestion
        placeholder="追加する管理者を選択"
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +        placeholder="管理者から削除"
```suggestion
        placeholder="削除する管理者を選択"
```

2022-04-04 13:50 UTC, FujishigeTemma commented on src/stores/admin.ts
> +import axios from 'axios'
TODO: `apis`を使って書き直す

2022-04-04 14:19 UTC, mehm8128 commented on src/pages/Admin.vue
> +import { useUserStore } from '../stores/user'
下2つだけ「モジュール '@/stores/admin' またはそれに対応する型宣言が見つかりません。」になってしまいました...

2022-04-04 14:46 UTC, mehm8128 commented on src/App.vue
> +          <router-link to="/transactions?pageIndex=1"
?pageIndex=1を消してcomponent側では1をデフォルトで持っておくということですか？

2022-04-04 14:47 UTC, mehm8128 commented on src/stores/admin.ts
> +import axios from 'axios'
OpenAPI generatorについてなのですが、使い方がよく分かってなくて例えばこんな感じ、みたいな感じでGETとPOSTを1つずつくらい実装してみていただきたいです

2022-04-04 19:16 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +    userStore.getUsers()
すみません、↑は間違ったアプローチだったので忘れてください。
piniaのdefinePropsの中に書くstateの初期化は、definePropsが初めて呼ばれたときだけ実行されるので、definePropsの中に書いてしまって問題ないです。そうすると、requestの終了を待ちたい（=storeの初期化を待ちたい）場面が出てくると思うんですが、そのときはloadingみたいなstateを生やせばよいです。

2022-04-04 19:17 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +    userStore.getUsers()
もともとのアプローチの理解としてはそれであってます。

2022-04-04 21:12 UTC, FujishigeTemma commented on src/pages/Admin.vue
> +import { useUserStore } from '../stores/user'
修正したものをpushしておきました。

2022-04-11 10:04 UTC, FujishigeTemma approved these changes

2022-04-11 10:06 UTC, merged